package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"juice-subgraph/graph/model"
)

// FindJuiceByID is the resolver for the findJuiceByID field.
func (r *entityResolver) FindJuiceByID(ctx context.Context, id string) (*model.Juice, error) {
	panic(fmt.Errorf("not implemented: FindJuiceByID - findJuiceByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
