// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ingredient struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Juice struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Ingredients []*Ingredient `json:"ingredients"`
}

func (Juice) IsEntity() {}
