package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"ingredients-subgraph/graph/model"
)

// Ingredients is the resolver for the ingredients field.
func (r *queryResolver) Ingredients(ctx context.Context) ([]*model.Ingredient, error) {
	dummyIngredients := []*model.Ingredient{
		{
			ID:   "1",
			Name: "Orange",
		},
		{
			ID:   "2",
			Name: "Apple",
		},
		{
			ID:   "3",
			Name: "Water",
		},
		{
			ID:   "4",
			Name: "Sugar",
		},
		{
			ID:   "5",
			Name: "OpenSourceExtract",
		},
	}

	return dummyIngredients, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
